version: "3"
services:
  api:
    image: diary_api_api:latest
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
    environment:  
      - NODE_ENV=production
    links:
      - db
  db:
    image: mongo:3.4
    volumes:
      - './mongodb_data:/data/db'
